version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - user_api_network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: user_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - user_api_network
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: user_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-user_api}
      POSTGRES_USER: ${DB_USERNAME:-user_api}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_api_network

  redis:
    image: redis:alpine
    container_name: user_api_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - user_api_network

networks:
  user_api_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
